In [3]:
import torch
import torchvision

# extra modeling and data reading tools from pytorch
from torch import nn

import numpy as np

In [33]:
w1.detach().numpy()

array([[0.7150685 , 0.14390977, 0.77272457, 0.95163095, 0.4299921 ,
        0.6599747 , 0.59857416, 0.7345963 , 0.2861966 , 0.22010808],
       [0.16153437, 0.8918415 , 0.18113112, 0.5824676 , 0.28988472,
        0.532983  , 0.6579713 , 0.1719475 , 0.97903913, 0.7765144 ],
       [0.2021024 , 0.5248751 , 0.28198358, 0.63730586, 0.47586796,
        0.65349156, 0.39417702, 0.73404247, 0.14967076, 0.40854535],
       [0.3067059 , 0.95962614, 0.01664586, 0.30141404, 0.21821408,
        0.47555348, 0.68128675, 0.39033276, 0.5701695 , 0.14439178],
       [0.22087474, 0.49741796, 0.5869911 , 0.8950301 , 0.8292208 ,
        0.09844429, 0.1338869 , 0.94267654, 0.9851758 , 0.2676462 ],
       [0.4398276 , 0.31502193, 0.36683002, 0.87533325, 0.8425604 ,
        0.97490317, 0.46412724, 0.10208702, 0.25485617, 0.82248664],
       [0.3017859 , 0.76164615, 0.51203007, 0.7630864 , 0.647776  ,
        0.1816636 , 0.7390297 , 0.7603484 , 0.12170932, 0.95167285],
       [0.76241416, 0.7420421 , 0.6868158

In [22]:
sampled_weights

array([[0.72354981, 0.14349907, 0.76099918, 0.93069964, 0.42950667,
        0.66527737, 0.61440552, 0.73531753, 0.28370657, 0.21018726],
       [0.1700156 , 0.89143071, 0.16940574, 0.5615363 , 0.28939926,
        0.53828567, 0.67380266, 0.17266871, 0.97654915, 0.7665936 ],
       [0.21058363, 0.52446436, 0.27025822, 0.61637456, 0.47538252,
        0.65879421, 0.41000836, 0.73476371, 0.14718075, 0.39862454],
       [0.31518712, 0.95921539, 0.00492048, 0.28048277, 0.21772863,
        0.48085615, 0.69711809, 0.39105398, 0.56767951, 0.13447095],
       [0.22935598, 0.49700726, 0.57526571, 0.87409877, 0.82873532,
        0.10374696, 0.14971825, 0.94339774, 0.98268578, 0.25772539],
       [0.44830882, 0.31461122, 0.35510465, 0.85440195, 0.84207491,
        0.98020585, 0.47995859, 0.10280823, 0.25236616, 0.81256578],
       [0.31026712, 0.76123544, 0.50030472, 0.7421551 , 0.64729051,
        0.18696627, 0.75486108, 0.7610696 , 0.11921931, 0.94175199],
       [0.77089545, 0.74163138, 0.6750904

In [26]:
weights

tensor([[0.7235, 0.1435, 0.7610, 0.9307, 0.4295, 0.6653, 0.6144, 0.7353, 0.2837,
         0.2102],
        [0.1700, 0.8914, 0.1694, 0.5615, 0.2894, 0.5383, 0.6738, 0.1727, 0.9765,
         0.7666],
        [0.2106, 0.5245, 0.2703, 0.6164, 0.4754, 0.6588, 0.4100, 0.7348, 0.1472,
         0.3986],
        [0.3152, 0.9592, 0.0049, 0.2805, 0.2177, 0.4809, 0.6971, 0.3911, 0.5677,
         0.1345],
        [0.2294, 0.4970, 0.5753, 0.8741, 0.8287, 0.1037, 0.1497, 0.9434, 0.9827,
         0.2577],
        [0.4483, 0.3146, 0.3551, 0.8544, 0.8421, 0.9802, 0.4800, 0.1028, 0.2524,
         0.8126],
        [0.3103, 0.7612, 0.5003, 0.7422, 0.6473, 0.1870, 0.7549, 0.7611, 0.1192,
         0.9418],
        [0.7709, 0.7416, 0.6751, 0.0387, 0.9662, 0.5604, 0.3682, 0.9514, 0.7171,
         0.0618],
        [0.6861, 0.5735, 0.3638, 0.2504, 0.3594, 0.6427, 0.5142, 0.6041, 0.9140,
         0.3776],
        [0.5830, 0.5489, 0.4062, 0.4856, 0.2860, 0.2915, 0.5058, 0.2516, 0.8805,
         0.8037]], dtype=tor

In [20]:
class MyModule(nn.Module):
    def __init__(self, weights):
        super(MyModule, self).__init__()

        self.linear = nn.Linear(weights.shape[1], weights.shape[0])
        with torch.no_grad():
            self.linear.weight.copy_(weights)
        
    def forward(self, x):
        x = self.linear(x)
        return x

sampled_weights = np.random.random((10, 10))
weights = torch.from_numpy(sampled_weights)
#weights = torch.randn(10, 10)
model = MyModule(weights)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-1)

out = model(torch.randn(1, 10))
out.mean().backward()

for name, param in model.named_parameters():
    print(name, param.grad)

w0 = model.linear.weight.clone()
optimizer.step()
w1 = model.linear.weight.clone()
print(w1 - w0)

linear.weight tensor([[ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
        [ 0.0848, -0.0041, -0.1173, -0.2093, -0.0049,  0.0530,  0.1583,  0.0072,
         -0.0249, -0.0992],
     

In [28]:
optimizer.step()
w2 = model.linear.weight.clone()
print(w2 - w1)

tensor([[-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  0.0004,  0.0117,  0.0209,  0.0005, -0.0053, -0.0158, -0.0007,
          0.0025,  0.0099],
        [-0.0085,  